// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9y9FED7L-s0unONweN-5LhmwEdipXYUo',
    appId: '1:209409669834:web:9e33eba07509ee28a29233',
    messagingSenderId: '209409669834',
    projectId: 'wazenfapp',
    authDomain: 'wazenfapp.firebaseapp.com',
    storageBucket: 'wazenfapp.firebasestorage.app',
    measurementId: 'G-T55QBE1SGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4hbU_8mTr7OQmMfGoosU9KOfjim5E1us',
    appId: '1:209409669834:android:60fc80371848796ca29233',
    messagingSenderId: '209409669834',
    projectId: 'wazenfapp',
    storageBucket: 'wazenfapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wcfszUhNhA8plluVsd-UAlqgpJsxs20',
    appId: '1:209409669834:ios:fbb718e5d679e61ea29233',
    messagingSenderId: '209409669834',
    projectId: 'wazenfapp',
    storageBucket: 'wazenfapp.firebasestorage.app',
    iosBundleId: 'com.feras12.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9y9FED7L-s0unONweN-5LhmwEdipXYUo',
    appId: '1:209409669834:web:7aa6c1bb40e5b685a29233',
    messagingSenderId: '209409669834',
    projectId: 'wazenfapp',
    authDomain: 'wazenfapp.firebaseapp.com',
    storageBucket: 'wazenfapp.firebasestorage.app',
    measurementId: 'G-Q6L7R0SP5C',
  );
}
